# Tensors
[URL](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)


Tensors are a specialized data structure that are very similar to arrays and matrices.
In PyTorch, we use tensors to encode the inputs and outputs of model, as well as the model's parameters/

Tensors are similar to NumPy's ndarrays, except that tensors can run on GPUs or other hardware accelerators.
In fact, tesnsors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see [Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)).
Tensors are also optimized for automatic differentiation (we'll see more about that later in the Autograd section).
If you're familiar with ndarrays, you'll be right at home with the Tensor API. 
If not follow along!


- tensorsとNumPyはとても似ていて，違う点はGPUやその他のハードウェアアクセラレーションを利用できるかどうか．
- メモリも共有しており，データをコピーする必要がない．(無駄にメモリを消費しない?)
- tensorsは自動微分のために最適化される．

In [1]:
import torch
import numpy as np

In [6]:
print(f'torch: {torch.__version__}')
print(f'np: {np.__version__}')

torch: 1.8.1
np: 1.20.2


## Initializing a Tensor
Tensors can be initialized in various ways.

tesorは様々な方法で初期化出来る．
直接変換したり，numpy形式や別のtensorからも可能である

### Directly from data
Tensors can be created directly from data.
The data type is automatically inferred.

tensorはデータから直接作ることができる．
データタイプは自動的に推論されて決まる．

In [2]:
# Directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

### From a NumPy array
Tensors can be created from NumPy arrays (and vice versa - see [Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label))

tensorはNumPyからも可能．詳細はURLを確認する．

In [3]:
# From a NumPy array
np_array = np.array([[1, 2], [3, 4]])
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

### From another tensor
The new tensor retains the proprties (sahpe, datatype) of the argument tensor, unless explicitly overridden.

明示的に上書きしない限り，新しいtensorは元のtensorの引数の性質(形やデータタイプ)を維持する．

In [56]:
# retians the properties of x_data
x_ones = torch.ones_like(x_data)
print(f'Ones Tensor:\n {x_ones}')

# overrides the datatype pf x_data
x_rand = torch.rand_like(x_data, dtype=torch.float32)
print(f'Random Tensor: \n {x_rand} \n')

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])
Random Tensor: 
 tensor([[0.5150, 0.2971],
        [0.6060, 0.6592]]) 



### With random or constant value
`shape` is a tuple of tensor dimensions.
In the functions below, it determines the dimensionality of the output tensor.

`shape`はtensorの次元を表したタプルである．
以下の関数を用いれば，出力されるtensorの次元を決定することができる．

In [23]:
shape = (2, 2, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeors Tensor: \n {zeros_tensor} \n')

Random Tensor: 
 tensor([[0.2763, 0.6561],
        [0.0277, 0.3908]]) 

Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.]]) 

Zeors Tensor: 
 tensor([[0., 0.],
        [0., 0.]]) 



In [31]:
tensor1 = torch.ones((2))        # 2 vector
tensor2 = torch.ones((2, 3))     # 2x3 matrix
tensor3 = torch.ones((2, 3, 4))  # 2x3x4 tensor
tensor4 = torch.ones((2, 3, ))   # 2x3 matrix
print(f'shape (2): \n {tensor1}\n')
print(f'shape (2, 3):\n  {tensor2}\n')
print(f'shape (2, 3, 4)):\n  {tensor3}\n')
print(f'shape (2, 3, ):\n  {tensor4}\n')

shape (2): 
 tensor([1., 1.])

shape (2, 3):
  tensor([[1., 1., 1.],
        [1., 1., 1.]])

shape (2, 3, 4)):
  tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

shape (2, 3, ):
  tensor([[1., 1., 1.],
        [1., 1., 1.]])



## Attributes of a Tensor
Tensor attributes descrive their shape, datatype, and the device on which they are stored.

tensorのアトリビュートには，shape, datatype, device(保存されている場所を示す)がある．

In [33]:
tensor = torch.rand(3, 4)
print(tensor)
print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

tensor([[0.5872, 0.8028, 0.5084, 0.9690],
        [0.5210, 0.9562, 0.8006, 0.3064],
        [0.9844, 0.2014, 0.6365, 0.6765]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operation on Tensors
Over 100 tensor operation, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively descrived [here](https://pytorch.org/docs/stable/torch.html)

Each of these operation can be run on the GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using `.to` method (after checking for GPU availability).
Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

tensor型を操作する方法はたくさんあり，算術や線形代数，行列操作などがある．
詳細はURLに載っている．
それぞれの操作はGPU上で行うことができる．
デフォルトでは，tensorはCPU上で作成されるため，GPUが使えるかを確認したのちに，`.to`メソッドを用いて，明示的にGPU上に移動させる必要がある．
大きいtensorをデバイス間で移動することは，時間やメモリの観点からコストがかかることに注意する．

In [36]:
# We move our tensor to the GPU if available
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'now using device: {device}')

if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    tensor = tensor.to(device)

now using device: cpu


Try out some of the operation from the list.
If you're familiar with the NumPy API, you'll find the Tensor API a breeze to use.

NumPyの操作に慣れていれば，tensorの操作も簡単にできる

### Standard numpy-like indexing and slicing

In [40]:
tensor = torch.ones((4, 3))
print(f'tensor: \n {tensor}\n')
print(f'First row: \n {tensor[0]}\n')
print(f'First column: \n {tensor[:, 0]} \n')
print(f'Last column: \n {tensor[:, -1]} \n ')

tensor[:, 1] = 0
print(tensor)

tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

First row: 
 tensor([1., 1., 1.])

First column: 
 tensor([1., 1., 1., 1.]) 

Last column: 
 tensor([1., 1., 1., 1.]) 
 
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


### Joining tensors
You can use `torch.cat` to concatenate a sequence of tensors along a given dimension.
See also [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html), another tensor joining op(up?) that is subtly different from `torch.cat`.

`torch.cat`を使えば，指定した次元に対してtensorを結合することができる．
`torch.stack`は，新しい次元に沿ってtensorを結合させる

In [51]:
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(f't: \n {t} \n')

# torch.cat(tensor, dim=1) -> 列に追加(concatenate column)
t1 = torch.cat([t, t, t], dim=1)
print(f't1: \n {t1} \n')

# torch.cat(tensor, dim=0) -> 行に追加(concatenate row)
t0 = torch.cat([t, t, t], dim=0)
print(f't0: \n {t0}, \n')

t: 
 tensor([[1., 2., 3.],
        [4., 5., 6.]]) 

t1: 
 tensor([[1., 2., 3., 1., 2., 3., 1., 2., 3.],
        [4., 5., 6., 4., 5., 6., 4., 5., 6.]]) 

t0: 
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 2., 3.],
        [4., 5., 6.],
        [1., 2., 3.],
        [4., 5., 6.]]), 



In [57]:
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])

# torch.stack(tensor, dim=1) -> 行ごとに追加する
ts1 = torch.stack([t, t, t], dim=1)
print(f'ts1: \n {ts1} \n')

# torch.stack(tensor, dim=0) -> 一つの塊として追加する
ts0 = torch.stack([t, t, t], dim=0)
print(f'ts0: \n {ts0} \n')

ts1: 
 tensor([[[1., 2., 3.],
         [1., 2., 3.],
         [1., 2., 3.]],

        [[4., 5., 6.],
         [4., 5., 6.],
         [4., 5., 6.]]]) 

ts0: 
 tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]]) 



### Single-element tensors
If you have a one-element tensor, for example by aggregating all value of a tensor into one value, you can convert it to a Python numerical value using `item()`.

もしtensorが一つの要素しかない場合(集計など)は，`item()`を使えば，Pythonの数値型として取得できる．

In [61]:
tensor = torch.rand((3, 4))
print(tensor)
agg = tensor.sum()
agg_item = agg.item()
print(f'agg: {agg}, type(agg): {type(agg)}')
print(f'agg_item: {agg_item}, type(agg_item): {type(agg_item)}')

tensor([[0.4555, 0.1349, 0.2650, 0.3512],
        [0.7351, 0.2268, 0.9525, 0.7250],
        [0.1857, 0.6891, 0.9155, 0.9184]])
agg: 6.5546793937683105, type(agg): <class 'torch.Tensor'>
agg_item: 6.5546793937683105, type(agg_item): <class 'float'>


### In-place operating
Operations that store the result into the operand are called in-place.
They are denoted by `_` suffix.
For example: `x.copy_(y)`, `x.t_()`, will change `x`

結果をオペランド(: 演算の対象となるもの)に保存する操作は，インプレースという．
接尾辞`_`で表現する．

In [62]:
tensor = torch.ones((2, 3))
print(tensor, '\n')
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[6., 6., 6.],
        [6., 6., 6.]])


#### Note
In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history.
Hence, their use is discourage.

インプレース操作はメモリを節約するが，履歴はすぐに失われるため，導関数(derivative)を計算する時に問題が発生する可能性がある．
よって使用をお勧めしない．

## Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

CPU上とのtensorとNumPy arrayはメモリの位置を共有することができ，片方を変えればもう片方も変わる．

### Tensor to NumPy array

In [63]:
t = torch.ones(5)
print(f't: {t}')
n = t.numpy()
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tenosr reflects in the NumPy array.

tensorの変換はnumpyに反映される

In [64]:
t.add_(1)
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to Tensor

In [66]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f't: {t}')
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


Changes in the NumPy array reflects in the tensor.

NumPyの変換はtensorにも反映される．

In [67]:
np.add(n, 1, out=n)
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
